spring:
  application:
    name: convenience-store

  datasource:
    url:  jdbc:mysql://localhost:3306/convenience_store
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  file:
    name: logs/covenience-store.log

  level:
    root: INFO
    com.store.conveniencestore: DEBUG

  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 50
      total-size-cap: 1GB

